apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: moto-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: flask-app
          image: layouniwiem/devops_riders:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FLASK_APP
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FLASK_ENV
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SECRET_KEY
            - name: DATABASE_URL
              value: "mysql+pymysql://user:pass@mariadb:3306/dbname" # ← ou injectée via configMap

          envFrom:
            - secretRef:
                name: db-credentials

          volumeMounts:
            - name: flask-uploads
              mountPath: /app/static/img

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi

      volumes:
        - name: flask-uploads
          persistentVolumeClaim:
            claimName: flask-uploads-pvc
