apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-uploads-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/flask-uploads
  persistentVolumeReclaimPolicy: Retain
