apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: moto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: docker.io/layouniwiem/moto-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: GUNICORN_CMD_ARGS
          value: "--bind=0.0.0.0:5000 --workers=2 --timeout=120 --keep-alive=2 --preload --access-logfile -"
        - name: MYSQL_HOST
          value: "mariadb.moto-app.svc.cluster.local"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_DEBUG
          value: "1"
        resources:
          requests:
            memory: "256Mi"  # Augmenté
            cpu: "500m"      # Augmenté
          limits:
            memory: "512Mi"  # Augmenté
            cpu: "1000m"     # Augmenté
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 90
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5