apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: moto-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: docker.io/layouniwiem/moto-app:latest  # Remplace par la bonne image/tag
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: MYSQL_DATABASE
          - name: MYSQL_HOST
            value: mariadb  # Nom du service MariaDB
          - name: FLASK_ENV
            value: production
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
