apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: moto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: docker.io/layouniwiem/moto-app:latest  # Correction du nom d'image
          ports:
          - containerPort: 5000
          env:
          - name: GUNICORN_CMD_ARGS  # Correction du nom de variable
            value: "--workers=2 --timeout=120 --keep-alive=2 --bind=0.0.0.0:5000"
          - name: MYSQL_HOST  # Correction du nom de variable
            value: "mariadb.moto-app.svc.cluster.local"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60  # Délai plus long
            periodSeconds: 10
            failureThreshold: 12     # 120s max

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 90  # Délai très long
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health 
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
          - name: GUNICORN_CMD_ARGS
            value: "--workers=2 --timeout=120 --keep-alive=2 --bind=0.0.0.0:5000 --preload"