apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: moto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: __IMAGE__
        ports:
        - containerPort: 5000
        env:
        - name: GUNICORN_CMD_ARGS
          value: "--bind=0.0.0.0:5000 --workers=2 --timeout=120 --keep-alive=2 --preload --access-logfile -"
        - name: MYSQL_HOST
          value: "mariadb.moto-app.svc.cluster.local"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_DATABASE
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_DEBUG
          value: "0"  # Set to 0 for production
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Use /ready for startup probe (no DB dependency)
        startupProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 12
          timeoutSeconds: 5
        # Use /health for liveness probe (with DB check)
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10
        # Use /ready for readiness probe initially, then /health
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3