apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moto-app-ingress
  namespace: moto-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Headers de sécurité recommandés
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - moto-app.internal
    - moto-app.example.com
    secretName: moto-app-tls
  rules:
  - host: moto-app.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app
            port:
              number: 80
      - path: /metrics
        pathType: Exact  # Changé en Exact pour plus de précision
        backend:
          service:
            name: flask-app
            port:
              number: 5000
  - host: moto-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app
            port:
              number: 80