apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: moto-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS moto_db;
    USE moto_db;

    CREATE TABLE IF NOT EXISTS user (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(64) UNIQUE NOT NULL,
        email VARCHAR(120) UNIQUE NOT NULL,
        password_hash VARCHAR(128)
    );

    CREATE TABLE IF NOT EXISTS moto (
        id INT AUTO_INCREMENT PRIMARY KEY,
        marque VARCHAR(50) NOT NULL,
        modele VARCHAR(50) NOT NULL,
        annee INT NOT NULL,
        kilometrage INT,
        prix FLOAT NOT NULL,
        description TEXT,
        date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP,
        image_url VARCHAR(200)
    );

    INSERT INTO user (username, email, password_hash) VALUES 
    ('admin', 'admin@example.com', 'pbkdf2:sha256:260000$...'),
    ('user1', 'user1@example.com', 'pbkdf2:sha256:260000$...');

    INSERT INTO moto (marque, modele, annee, kilometrage, prix, description,image_url) VALUES 
    ('Honda', 'CBR 600RR', 2018, 15000, 8500, 'Excellent état', 'https://...'),
    ('Yamaha', 'MT-07', 2020, 8000, 6500, 'Première main', 'https://...');
