---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-uploads-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  hostPath:
    path: /mnt/data/flask-uploads
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-uploads-pvc
  namespace: moto-app
spec:
  accessModes:
    - ReadWriteOnce  # Changé de ReadWriteMany à ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
