---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-uploads-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/flask-uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-uploads-pvc
  namespace: moto-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
