# handlers file for roles/docker

# roles/monitoring/handlers/main.yml
---
- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes