# roles/kubernetes/tasks/main.yml
---
- name: Installation des prérequis K3s
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
    state: present
    
- name: Configuration système pour K3s
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes
    
- name: Installation de K3s (Master)
  shell: |
    curl -sfL https://get.k3s.io | sh -s - \
      --disable=traefik \
      --write-kubeconfig-mode=644 \
      --advertise-address={{ ansible_host }}
  args:
    creates: /usr/local/bin/k3s
  when: k3s_type == "master"
  
- name: Ouverture des ports Kubernetes
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 6443   # Kubernetes API
    - 80     # HTTP
    - 443    # HTTPS
    - 10250  # Kubelet
    
- name: Attendre que K3s soit disponible
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    timeout: 300
  when: k3s_type == "master"
  
- name: Récupérer le kubeconfig
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ./k3s.yaml
    flat: yes
  when: k3s_type == "master"

- name: Installation de NGINX Ingress Controller
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: k3s_type == "master"
  
- name: Création du namespace pour l'application
  kubernetes.core.k8s:
    name: moto-app
    api_version: v1
    kind: Namespace
    state: present
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: k3s_type == "master"

# roles/kubernetes/handlers/main.yml
---
- name: restart k3s
  service:
    name: k3s
    state: restarted
  when: k3s_type == "master"