---
    # 1️ Définir un répertoire temporaire sûr pour Ansible
    - name: Définir un répertoire temporaire alternatif pour Ansible
      set_fact:
        ansible_remote_tmp: "/tmp/.ansible"

    - name: Créer le répertoire temporaire Ansible
      file:
        path: "/tmp/.ansible"
        state: directory
        mode: '0777'

    # 2️ Installation de Git
    - name: Installer Git (Debian)
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Installer Git (RedHat)
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"

    # 3️ Configuration de Git (sans --global pour éviter les erreurs)
    - name: Configurer Git user.name
      shell: git config --system user.name "layouniwiem"

    - name: Configurer Git user.email
      shell: git config --system user.email "layouniwiem1993@gmail.com"

    # 4️ Autoriser Git à travailler dans /var/www/your-app2
    - name: Autoriser Git à accéder en toute sécurité au repo
      command: git config --global --add safe.directory /var/www/your-app2

    # 5️ Vérification et correction des permissions sur /var/www/
    - name: Vérifier et ajuster les permissions sur /var/www/
      file:
        path: /var/www/
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
      #Créer le répertoire de l'application si non existant
    - name: Créer le répertoire de l'application si non existant
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'


    # 6️ Cloner le repository de l'application
    - name: Cloner le repository de l'application
      git:
        repo: "{{ app_repo_url }}"
        dest: "{{ app_directory }}"
        force: yes
        version: main
      become: true
      become_user: www-data

    # 7️ Configurer Git safe.directory sans erreur de permission
    - name: Ajouter le répertoire Git à la liste des répertoires sûrs
      command: sudo -u www-data git config --local --add safe.directory {{ app_directory }}
      args:
        chdir: "{{ app_directory }}"

    # 8️ Vérifier et ajuster les permissions après clonage
    - name: Définir les permissions du répertoire de l'application
      file:
        path: "{{ app_directory }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
    #Construire les services Docker Compose
    - name: Construire les services Docker Compose
      command: docker-compose build
      args:
        chdir: "/var/www/your-app2/app"  # Dirige le chemin vers le répertoire contenant ton fichier docker-compose.yml
      become: true

    # (Facultatif) Démarrer les conteneurs après le build
    - name: Lancer les services Docker Compose
      command: docker-compose up -d --build
      args:
        chdir: "/var/www/your-app2/app"
      become: true
    # 9️ Installation de Nginx
    - name: Installer Nginx (Debian)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Installer Nginx (RedHat)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    #  10 Configuration de Nginx
    - name: Copier le fichier de configuration Nginx
      template:
        src: "nginx-app.conf.j2"
        dest: "{{ nginx_config_file }}"
      notify:
        - Reload nginx

    - name: Créer un lien symbolique vers sites-enabled
      file:
        src: "{{ nginx_config_file }}"
        dest: "{{ nginx_site_enabled }}"
        state: link

    #  11 Tester la configuration Nginx
    - name: Tester la configuration Nginx
      command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: nginx_test.rc != 0

    #  12 Démarrer et activer Nginx
    - name: Démarrer et activer Nginx
      service:
        name: nginx
        state: started
        enabled: true

