---
- name: Vérifier si Docker est installé
  command: docker --version
  register: docker_installed
  ignore_errors: yes

- name: Installer les dépendances pour Docker
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  when: docker_installed.failed



- name: Installer la collection Ansible community.docker
  ansible.builtin.command: ansible-galaxy collection install community.docker
  changed_when: false

- name: Démarrer et activer Docker
  become: true
  systemd:
    name: docker
    enabled: yes
    state: started
