---
- name: Initialisation complète des serveurs
  hosts: all
  become: yes

  vars:
    node_exporter_version: "1.8.1"

  tasks:

    - name: Nettoyage du cache APT
      command: apt-get clean

    - name: Mise à jour du cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_result
      retries: 5
      delay: 10
      until: apt_result is succeeded

    - name: Installation des paquets essentiels
      apt:
        name:
          - vim
          - curl
          - wget
          - htop
          - git
          - python3
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - ufw
          - fail2ban
        state: present
        install_recommends: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Configuration du fuseau horaire
      timezone:
        name: Europe/Paris

    - name: Activation du pare-feu UFW par défaut
      ufw:
        state: enabled
        policy: deny

    - name: Autorisation du port SSH
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Autoriser le port Node Exporter (9100)
      ufw:
        rule: allow
        port: "9100"
        proto: tcp

    - name: Installation de Docker (clé GPG)
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Ajout du dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Mise à jour après ajout du dépôt Docker
      apt:
        update_cache: yes

    - name: Installation de Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Ajout de l'utilisateur courant au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Activation du service Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Configuration de fail2ban
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 5

          [sshd]
          enabled = true

    - name: Redémarrage de fail2ban
      service:
        name: fail2ban
        state: restarted
        enabled: yes

    - name: Téléchargement de Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extraction de Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Création d'un utilisateur pour Node Exporter
      user:
        name: node_exporter
        shell: /usr/sbin/nologin

    - name: Création du service systemd pour Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Rechargement de systemd
      systemd:
        daemon_reload: yes

    - name: Activation et démarrage de Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
