---
- hosts: 192.168.1.77
  become: yes
  tasks:
    - name: Copy kubeconfig to Jenkins VM
      copy:
        src: /tmp/k3s-config.yaml
        dest: /tmp/k3s-config.yaml
        owner: jenkins
        group: jenkins
        mode: '0600'